sonar.projectKey=CabPiz_kairos-labs
sonar.organization=kairoslabs

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/__tests__/**,**/__mocks__/**,**/*.test.ts,**/*.test.tsx,e2e/**,**/*.spec.ts,scripts/**
sonar.cpd.exclusions=lib/products/index.tsx
